import React from 'react';
import type { RuleResult } from '../api/types';

interface RuleResultsViewProps {
  ruleResults: RuleResult[];
  onSelectEvidence: (evidenceId: string, triggerElement: HTMLElement | null) => void;
}

export const RuleResultsView: React.FC<RuleResultsViewProps> = ({
  ruleResults,
  onSelectEvidence,
}) => {
  return (
    <section className="dashboard-section" aria-labelledby="rule-results-heading">
      <div className="section-header-box">
        <h2 id="rule-results-heading" className="section-title">
          Deterministic Rule Checks
        </h2>
        <p className="section-description">
          Five transparent deterministic checks executed across the sample. All five rules are shown.
          A completed check with zero signals indicates that no condition matched its specific formula;
          it is not a proof or assertion of overall claim correctness.
        </p>
      </div>

      <div className="rules-grid">
        {ruleResults.map((rule) => {
          const hasSignals = rule.signals && rule.signals.length > 0;
          return (
            <div
              key={rule.rule_id}
              className={`rule-card card ${hasSignals ? 'rule-card-signaled' : 'rule-card-clean'}`}
              id={`rule-section-${rule.rule_id}`}
            >
              <div className="rule-card-header">
                <div className="rule-title-group">
                  <span className="rule-id font-mono">{rule.rule_id}</span>
                  <h3 className="rule-name">{rule.name}</h3>
                </div>
                <div className="rule-status-group">
                  <span
                    className={`badge ${
                      rule.status === 'completed'
                        ? 'badge-success'
                        : 'badge-warning'
                    }`}
                  >
                    {rule.status}
                  </span>
                  <span className={`badge ${hasSignals ? 'badge-alert' : 'badge-neutral'}`}>
                    {rule.signals.length} {rule.signals.length === 1 ? 'signal' : 'signals'}
                  </span>
                </div>
              </div>

              <p className="rule-description">{rule.description}</p>

              <div className="rule-meta-box">
                <div className="rule-formula">
                  <strong>Formula:</strong> <code className="font-mono text-xs">{rule.formula}</code>
                </div>
                {Object.keys(rule.parameters).length > 0 && (
                  <div className="rule-parameters">
                    <strong>Parameters:</strong>
                    <ul className="param-list">
                      {Object.entries(rule.parameters).map(([k, v]) => (
                        <li key={k} className="param-item">
                          <code>{k}:</code> {String(v)}
                        </li>
                      ))}
                    </ul>
                  </div>
                )}
              </div>

              {/* Signals list */}
              <div className="rule-signals-section">
                <h4 className="signals-title">
                  Signals ({rule.signals.length})
                </h4>
                {rule.signals.length === 0 ? (
                  <p className="no-signals-msg text-muted">
                    No signals generated by this rule.
                  </p>
                ) : (
                  <div className="signals-list">
                    {rule.signals.map((signal) => (
                      <div key={signal.evidence_id} className="signal-item">
                        <div className="signal-header">
                          <span className="font-mono text-xs font-semibold">
                            {signal.evidence_id}
                          </span>
                          <span
                            className={`badge ${
                              signal.priority === 'review'
                                ? 'badge-danger'
                                : 'badge-info'
                            }`}
                          >
                            Priority: {signal.priority}
                          </span>
                        </div>
                        <p className="signal-message">{signal.message}</p>

                        <div className="signal-evidence-refs">
                          <span className="text-xs text-muted font-semibold">
                            Evidence Citations:
                          </span>
                          <div className="refs-chips">
                            {signal.evidence_refs.map((ref) => (
                              <button
                                key={ref}
                                type="button"
                                className="chip-ref"
                                onClick={(e) => onSelectEvidence(ref, e.currentTarget)}
                                title={`Jump to evidence: ${ref}`}
                              >
                                {ref}
                              </button>
                            ))}
                          </div>
                        </div>

                        {signal.limitations && signal.limitations.length > 0 && (
                          <div className="signal-limitations text-xs text-muted">
                            <em>Limitations:</em> {signal.limitations.join(' ')}
                          </div>
                        )}
                      </div>
                    ))}
                  </div>
                )}
              </div>

              {/* Missing evidence */}
              {rule.missing_evidence && rule.missing_evidence.length > 0 && (
                <div className="rule-missing-evidence">
                  <h4 className="text-xs font-semibold text-warning">
                    Missing Evidence Notes ({rule.missing_evidence.length})
                  </h4>
                  <ul className="text-xs text-muted">
                    {rule.missing_evidence.map((item, idx) => (
                      <li key={idx}>{item}</li>
                    ))}
                  </ul>
                </div>
              )}

              {/* Limitations */}
              {rule.limitations && rule.limitations.length > 0 && (
                <div className="rule-limitations">
                  <details className="text-xs text-muted">
                    <summary className="cursor-pointer font-semibold">
                      Rule Limitations ({rule.limitations.length})
                    </summary>
                    <ul className="mt-1">
                      {rule.limitations.map((lim, idx) => (
                        <li key={idx}>{lim}</li>
                      ))}
                    </ul>
                  </details>
                </div>
              )}
            </div>
          );
        })}
      </div>
    </section>
  );
};
