import { render, screen, fireEvent } from '@testing-library/react';
import { describe, it, expect, vi } from 'vitest';
import { RuleResultsView } from './RuleResultsView';
import { mockSuccessResponse } from '../test/fixtures';

describe('RuleResultsView', () => {
  it('renders all 5 deterministic checks with formulas and status', () => {
    const onSelect = vi.fn();
    render(
      <RuleResultsView
        ruleResults={mockSuccessResponse.rule_results}
        onSelectEvidence={onSelect}
      />
    );

    expect(screen.getByText('REF-001')).toBeInTheDocument();
    expect(screen.getByText('DATE-001')).toBeInTheDocument();
    expect(screen.getByText('REPEAT-001')).toBeInTheDocument();
    expect(screen.getByText('AMOUNT-001')).toBeInTheDocument();
    expect(screen.getByText('OUTLIER-001')).toBeInTheDocument();

    // Verify zero-signal completed message for REF-001
    expect(screen.getAllByText(/No signals generated by this rule/i)).toHaveLength(3);

    // Verify signal message for DATE-001
    expect(screen.getByText(/Service date 2015-10-01 is outside coverage period/i)).toBeInTheDocument();
  });

  it('triggers onSelectEvidence when evidence reference chip is clicked', () => {
    const onSelect = vi.fn();
    render(
      <RuleResultsView
        ruleResults={mockSuccessResponse.rule_results}
        onSelectEvidence={onSelect}
      />
    );

    const refChips = screen.getAllByRole('button', { name: 'ev:eob:/entry/0/resource/item/0/servicedDate' });
    expect(refChips.length).toBeGreaterThan(0);
    fireEvent.click(refChips[0]!);

    expect(onSelect).toHaveBeenCalledWith(
      'ev:eob:/entry/0/resource/item/0/servicedDate',
      expect.anything()
    );
  });
});
