from __future__ import annotations

import json
import re
from pathlib import Path

from packaging.requirements import Requirement
from packaging.utils import canonicalize_name
from packaging.version import Version


ROOT = Path(__file__).resolve().parents[2]
LOCK_ENTRY = re.compile(r"^([A-Za-z0-9][A-Za-z0-9._-]*)==([^\s\\]+)\s*\\?$")
SHA256_HASH = re.compile(r"--hash=sha256:[a-f0-9]{64}(?:\s*\\)?$")
LOCK_INSTALL = "python -m pip install --require-hashes -r requirements.lock"
AUDIT_COMMAND = [
    "python3",
    "-m",
    "pip_audit",
    "--strict",
    "--require-hashes",
    "--no-deps",
    "--disable-pip",
    "--progress-spinner",
    "off",
    "-r",
    "requirements.lock",
]


def _direct_requirements(path: Path) -> list[Requirement]:
    requirements: list[Requirement] = []
    for raw_line in path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#"):
            continue
        if line.startswith("-r "):
            requirements.extend(_direct_requirements(ROOT / line.removeprefix("-r ")))
            continue
        requirements.append(Requirement(line))
    return requirements


def _locked_requirements() -> dict[str, tuple[Version, str]]:
    lines = (ROOT / "requirements.lock").read_text(encoding="utf-8").splitlines()
    entries: dict[str, tuple[Version, str]] = {}
    for index, line in enumerate(lines):
        match = LOCK_ENTRY.fullmatch(line)
        if match is None:
            continue
        next_entry = next(
            (candidate for candidate in range(index + 1, len(lines)) if LOCK_ENTRY.fullmatch(lines[candidate])),
            len(lines),
        )
        block = "\n".join(lines[index:next_entry])
        name = canonicalize_name(match.group(1))
        assert name not in entries, f"duplicate locked requirement: {name}"
        assert any(SHA256_HASH.search(hash_line) for hash_line in lines[index:next_entry]), name
        entries[name] = (Version(match.group(2)), block)
    return entries


def test_lock_is_python312_exact_complete_hashed_and_matches_direct_inputs() -> None:
    lock_text = (ROOT / "requirements.lock").read_text(encoding="utf-8")
    assert "autogenerated by pip-compile with Python 3.12" in lock_text
    locked = _locked_requirements()
    assert locked
    for requirement in _direct_requirements(ROOT / "requirements-agent.txt"):
        name = canonicalize_name(requirement.name)
        assert name in locked
        assert locked[name][0] in requirement.specifier
    assert locked["pip-audit"][0] == Version("2.10.1")


def test_direct_manifest_documents_exact_regeneration_and_strict_audit() -> None:
    manifest = (ROOT / "requirements-agent.txt").read_text(encoding="utf-8")
    assert "pip-tools==7.5.0" in manifest
    assert "python -m piptools compile --upgrade --generate-hashes --allow-unsafe" in manifest
    assert "pip-audit==2.10.1" in manifest
    assert "python -m pip_audit --strict --require-hashes --no-deps --disable-pip" in manifest


def test_python_installing_workflows_use_only_hash_locked_graph() -> None:
    workflow_files = sorted((ROOT / ".github" / "workflows").glob("*.y*ml"))
    install_lines = [
        line.strip().removeprefix("run: ")
        for workflow in workflow_files
        for line in workflow.read_text(encoding="utf-8").splitlines()
        if "pip install" in line
    ]
    assert install_lines
    assert all(line == LOCK_INSTALL for line in install_lines)


def test_required_project_security_check_is_strict_hash_locked_audit() -> None:
    project = json.loads((ROOT / ".ai" / "project.json").read_text(encoding="utf-8"))
    audit_checks = [check for check in project["security"]["checks"] if check["name"] == "hash-locked dependency audit"]
    assert audit_checks == [
        {
            "name": "hash-locked dependency audit",
            "command": AUDIT_COMMAND,
            "cwd": ".",
            "required": True,
        }
    ]
    assert "--ignore-vuln" not in audit_checks[0]["command"]
